########################################
#              FreeForAll Version 2.0
#
# If you require any help leave a comment on the forums
# http://dev.bukkit.org/bukkit-plugins/freeforallgametype/
########################################

########################################
#
#                  Chat Messages
#
########################################

ChatPrefix: '&f[&b&lFFA&f] &6'

NoPerms: '&c&lYou don''t have permission'

FFAJoinMessage: '&a&lYou joined the FFA'

FFALeaveMessage: '&c&lYou left the FFA'

AlreadyInFFA: '&c&lYou are already in the FFA'

NotInFFA: '&c&lYou are not in the FFA'

########################################
#
#                  Kits
#
########################################

KitsEnabled: false

kitMenuPrefix: '&8Kit Menu'

kits:
  kit1:
    iconSlotID: 10
    descSlotID: 19
    iconID: 268
    iconName: '&a&lSelect Tank Kit'
    descID: 311
    descName: '&a&lTank Kit'
    descLore:
      - '&6&lIncludes:'
      - '&7Wooden Sword'
      - '&bDiamond Helmet'
      - '&bDiamond ChestPlate'
      - '&bDiamond Leggings'
      - '&bDiamond Boots'
  kit2:
    iconSlotID: 12
    descSlotID: 21
    iconID: 267
    iconName: '&a&lSelect Knight Kit'
    descID: 299
    descName: '&a&lKnight Kit'
    descLore:
      - '&6&lIncludes:'
      - '&7Iron Sword'
      - '&bLeather Helmet'
      - '&bLeather ChestPlate'
      - '&bLeather Leggings'
      - '&bLeather Boots'
  kit3:
    iconSlotID: 14
    descSlotID: 23
    iconID: 261
    iconName: '&a&lSelect Archer Kit'
    descID: 303
    descName: '&a&lArcher Kit'
    descLore:
      - '&6&lIncludes:'
      - '&7Bow &5&o- Infinity I'
      - '&bChainMail Helmet'
      - '&bChainMail ChestPlate'
      - '&bChainMail Leggings'
      - '&bChainMail Boots'
  kit4:
    iconSlotID: 16
    descSlotID: 25
    iconID: 276
    iconName: '&a&lSelect Rouge Kit'
    descID: 295
    descName: '&a&lRouge Kit'
    descLore:
      - '&6&lIncludes:'
      - '&7Diamond Sword &5&o- KnockBack II'
      - '&7Seeds &5&o- Sharpness IV'




